### ISSUE TITLE
PysimpleCV example CV data export problem 

### ISSUE THREAD

**Issue by abhishekk79** [kevinsmia1939/PySimpleCV#1]
[example_CV.txt](https://github.com/user-attachments/files/16538097/example_CV.txt)

I tried to open this file for CV analysis and encountered an error in VScode:

** File "c:\Users\abhis\Downloads\PySimpleCV-1.0.7\PySimpleCV\PySimpleCV_main_func.py", line 62, in CV_file2df
    df_CV = df_CV.dropna()
AttributeError: 'numpy.ndarray' object has no attribute 'dropna' **

What is happening?

**Comment by kevinsmia1939** [comment]
Hi,
Try the download from the main branch. I add the fix to it in [dfbadfa728342d0926f7ab846089619c9c4657c8](https://github.com/kevinsmia1939/PySimpleCV/commit/dfbadfa728342d0926f7ab846089619c9c4657c8)

**Comment by abhishekk79** [comment]
Hey!

The GUI opens likes this:

![pysimplecv docking issue] (https://github.com/user-attachments/assets/1f2a0be8-9dc7-42a8-b5b2-f037bdce1c04)

I can't see the top menu bar at all. I can't seem to drag it down either.
