### ISSUE TITLE
PysimpleCV GUI window docked at the top.

### ISSUE THREAD

**Issue by abhishekk79** [kevinsmia1939/PySimpleCV#2]
Hey!

The GUI opens likes this:

![pysimplecv docking issue] (https://github.com/user-attachments/assets/1f2a0be8-9dc7-42a8-b5b2-f037bdce1c04)

I can't see the top menu bar at all. I can't seem to drag it down either.

_Originally posted by @abhishekk79 in https://github.com/kevinsmia1939/PySimpleCV/issues/1#issuecomment-2278415588_

**Comment by kevinsmia1939** [comment]
It seems like you just need to drag the window down, I am not using windows, so not sure what key combination to hold to drag it down.

**Comment by abhishekk79** [comment]
I can't drag it down, the window is stuck there.

**Comment by kevinsmia1939** [comment]
I think that it is because the UI is too big, and the inability to resize the window does not help.
But I have largely abandon PySimpleCV and working on PySimpleEChem. So I will close this as I won't work on it anymore.
